### PR TITLE
feat: REUSE compliance

### PR DESCRIPTION
**Pull request by nicorikken**
Add additional license information to the repository in accorance to best practices, validated using the REUSE tool: https://reuse.software/
This makes the repository eligible for a badge: https://api.reuse.software/

(Thanks for making the code available under a free software license)

### CODE REVIEW

**Comment by nicorikken** [comment]
Please feel free to comment so I can improve this PR. I consider this very much a work in progress. And hope to copy the effort to the other repositories as well.

**Comment by carmenbianca** [comment]
Hi, I'm one of the maintainers of REUSE, and I've worked with @nicorikken  before. Nico had asked me to take a peek at this.

Everything looks good, bar perhaps one thing that might cause some grief in the future:

```java
/*
 * Created by Ubique Innovation AG
 * https://www.ubique.ch
 * Copyright (c) 2020. All rights reserved.
 *
 * SPDX-FileCopyrightText: 2020 Ubique Innovation AG <https://www.ubique.ch>
 *
 * SPDX-License-Identifier: MPL-2.0
 */
```

This header appears a lot in the PR, and has the same copyright notice twice. I would suggest to either keep the old (first) copyright notice, or to replace it with the SPDX-style (second) copyright notice. Both are REUSE-compliant, except the old notice has two weird features:

- It does not list the copyright holder. Normal software copyright notices *usually* include the copyright symbol, the year of creation, the name of the copyright holder, and an internet contact address. 
- "All rights reserved" potentially clashes with the licence. Or at the very least, it sends a message contradictory to the spirit of the licence. I would personally leave this out, but it's unlikely to cause any grief.

Nico had also asked me this:

> One issue I had already: the *.license files for the images in
> calibration-app/app/src/main/res/mipmap-xxhdpi/ directory resulted in a
> failed Gradle build. Any suggestions specifically for resources in
> Android apps?

That's what the `.reuse/dep5` file is for. It's a bit unfortunate, but if it breaks, it breaks 🤷

**Comment by nicorikken** [comment]
@carmenbianca thanks for reviewing, I'll update the PR to reflect your copyright comments, by staying more true to the original copyright notice. I already adopted the `.reuse/dep5` pattern which solved the `.png` issue.

**Comment by nicorikken** [comment]
I refactored the headers to be more human-readable, while still complying to best practices according to the REUSE tool:
```
Copyright (c) 2020 Ubique Innovation AG <https://www.ubique.ch>

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.

SPDX-License-Identifier: MPL-2.0
```

From my side this is now ready to be merged. You can then apply for a badge at the [REUSE API](https://api.reuse.software/).

Please let me know what you think of it. If you need something changed, I'm happy to update it.

**Comment by mxmehl** [comment]
Is there any blocker for merging it? This PR adds more legal clarity and eases reuse of the code.

**Comment by simonroesch** [comment]
To avoid the conflicts I created a new PR for this: https://github.com/DP-3T/dp3t-sdk-android/pull/93

**Pull request closed without merging**
