### PR TITLE
Allows full access to the exposure configuration

### PR DESCRIPTION
**Pull request by albertovecina**

### CODE REVIEW

**Comment by albertovecina** [comment]
Allow complete access for the exposure configuration values like the transmission risk scores or the dilation risk scores.

**Comment by albertovecina** [comment]
Could anyone help me what's the problem here?

**Comment by simonroesch** [comment]
What is the goal of this PR? It allows you to set the complete configuration, but those values are irrelevant, because the SDK only uses the attenuationDurationsInMinutes to decide if there was a contact or not. The thresholds for the attenuations can already be set with DP3T.setMatchingParameters(), therefore I don't see the benefit in allowing to configure the unused parameters.

**Comment by albertovecina** [comment]
> What is the goal of this PR? It allows you to set the complete configuration, but those values are irrelevant, because the SDK only uses the attenuationDurationsInMinutes to decide if there was a contact or not. The thresholds for the attenuations can already be set with DP3T.setMatchingParameters(), therefore I don't see the benefit in allowing to configure the unused parameters.
Is DP3T just using the thresholds? Or is the Google SDK who is just using the thresholds?

**Comment by simonroesch** [comment]
DP3T is just using the thresholds.

**Comment by albertovecina** [comment]
Thanks for your time.

**Pull request closed without merging**
